#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopQuaTang.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="SHOPQUATANG")]
	public partial class dbQLShopQuaTangDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCT_HOADON(CT_HOADON instance);
    partial void UpdateCT_HOADON(CT_HOADON instance);
    partial void DeleteCT_HOADON(CT_HOADON instance);
    partial void InsertTINTUC(TINTUC instance);
    partial void UpdateTINTUC(TINTUC instance);
    partial void DeleteTINTUC(TINTUC instance);
    partial void InsertCT_PHIEUNHAP(CT_PHIEUNHAP instance);
    partial void UpdateCT_PHIEUNHAP(CT_PHIEUNHAP instance);
    partial void DeleteCT_PHIEUNHAP(CT_PHIEUNHAP instance);
    partial void InsertDANHMUC(DANHMUC instance);
    partial void UpdateDANHMUC(DANHMUC instance);
    partial void DeleteDANHMUC(DANHMUC instance);
    partial void InsertHINHANH_SP(HINHANH_SP instance);
    partial void UpdateHINHANH_SP(HINHANH_SP instance);
    partial void DeleteHINHANH_SP(HINHANH_SP instance);
    partial void InsertHOADON(HOADON instance);
    partial void UpdateHOADON(HOADON instance);
    partial void DeleteHOADON(HOADON instance);
    partial void InsertKHACHHANG(KHACHHANG instance);
    partial void UpdateKHACHHANG(KHACHHANG instance);
    partial void DeleteKHACHHANG(KHACHHANG instance);
    partial void InsertNHACUNGCAP(NHACUNGCAP instance);
    partial void UpdateNHACUNGCAP(NHACUNGCAP instance);
    partial void DeleteNHACUNGCAP(NHACUNGCAP instance);
    partial void InsertNHANVIEN(NHANVIEN instance);
    partial void UpdateNHANVIEN(NHANVIEN instance);
    partial void DeleteNHANVIEN(NHANVIEN instance);
    partial void InsertPHIEUNHAP(PHIEUNHAP instance);
    partial void UpdatePHIEUNHAP(PHIEUNHAP instance);
    partial void DeletePHIEUNHAP(PHIEUNHAP instance);
    partial void InsertSANPHAM(SANPHAM instance);
    partial void UpdateSANPHAM(SANPHAM instance);
    partial void DeleteSANPHAM(SANPHAM instance);
    #endregion
		
		public dbQLShopQuaTangDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["SHOPQUATANGConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public dbQLShopQuaTangDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbQLShopQuaTangDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbQLShopQuaTangDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbQLShopQuaTangDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<CT_HOADON> CT_HOADONs
		{
			get
			{
				return this.GetTable<CT_HOADON>();
			}
		}
		
		public System.Data.Linq.Table<TINTUC> TINTUCs
		{
			get
			{
				return this.GetTable<TINTUC>();
			}
		}
		
		public System.Data.Linq.Table<CT_PHIEUNHAP> CT_PHIEUNHAPs
		{
			get
			{
				return this.GetTable<CT_PHIEUNHAP>();
			}
		}
		
		public System.Data.Linq.Table<DANHMUC> DANHMUCs
		{
			get
			{
				return this.GetTable<DANHMUC>();
			}
		}
		
		public System.Data.Linq.Table<HINHANH_SP> HINHANH_SPs
		{
			get
			{
				return this.GetTable<HINHANH_SP>();
			}
		}
		
		public System.Data.Linq.Table<HOADON> HOADONs
		{
			get
			{
				return this.GetTable<HOADON>();
			}
		}
		
		public System.Data.Linq.Table<KHACHHANG> KHACHHANGs
		{
			get
			{
				return this.GetTable<KHACHHANG>();
			}
		}
		
		public System.Data.Linq.Table<NHACUNGCAP> NHACUNGCAPs
		{
			get
			{
				return this.GetTable<NHACUNGCAP>();
			}
		}
		
		public System.Data.Linq.Table<NHANVIEN> NHANVIENs
		{
			get
			{
				return this.GetTable<NHANVIEN>();
			}
		}
		
		public System.Data.Linq.Table<PHIEUNHAP> PHIEUNHAPs
		{
			get
			{
				return this.GetTable<PHIEUNHAP>();
			}
		}
		
		public System.Data.Linq.Table<SANPHAM> SANPHAMs
		{
			get
			{
				return this.GetTable<SANPHAM>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CT_HOADON")]
	public partial class CT_HOADON : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MA_HD;
		
		private int _MA_SP;
		
		private System.Nullable<int> _SL;
		
		private System.Nullable<double> _THANHTIEN_HD;
		
		private System.Nullable<double> _DONGIA;
		
		private EntityRef<HOADON> _HOADON;
		
		private EntityRef<SANPHAM> _SANPHAM;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMA_HDChanging(int value);
    partial void OnMA_HDChanged();
    partial void OnMA_SPChanging(int value);
    partial void OnMA_SPChanged();
    partial void OnSLChanging(System.Nullable<int> value);
    partial void OnSLChanged();
    partial void OnTHANHTIEN_HDChanging(System.Nullable<double> value);
    partial void OnTHANHTIEN_HDChanged();
    partial void OnDONGIAChanging(System.Nullable<double> value);
    partial void OnDONGIAChanged();
    #endregion
		
		public CT_HOADON()
		{
			this._HOADON = default(EntityRef<HOADON>);
			this._SANPHAM = default(EntityRef<SANPHAM>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MA_HD", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MA_HD
		{
			get
			{
				return this._MA_HD;
			}
			set
			{
				if ((this._MA_HD != value))
				{
					if (this._HOADON.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMA_HDChanging(value);
					this.SendPropertyChanging();
					this._MA_HD = value;
					this.SendPropertyChanged("MA_HD");
					this.OnMA_HDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MA_SP", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MA_SP
		{
			get
			{
				return this._MA_SP;
			}
			set
			{
				if ((this._MA_SP != value))
				{
					if (this._SANPHAM.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMA_SPChanging(value);
					this.SendPropertyChanging();
					this._MA_SP = value;
					this.SendPropertyChanged("MA_SP");
					this.OnMA_SPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SL", DbType="Int")]
		public System.Nullable<int> SL
		{
			get
			{
				return this._SL;
			}
			set
			{
				if ((this._SL != value))
				{
					this.OnSLChanging(value);
					this.SendPropertyChanging();
					this._SL = value;
					this.SendPropertyChanged("SL");
					this.OnSLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_THANHTIEN_HD", DbType="Float")]
		public System.Nullable<double> THANHTIEN_HD
		{
			get
			{
				return this._THANHTIEN_HD;
			}
			set
			{
				if ((this._THANHTIEN_HD != value))
				{
					this.OnTHANHTIEN_HDChanging(value);
					this.SendPropertyChanging();
					this._THANHTIEN_HD = value;
					this.SendPropertyChanged("THANHTIEN_HD");
					this.OnTHANHTIEN_HDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DONGIA", DbType="Float")]
		public System.Nullable<double> DONGIA
		{
			get
			{
				return this._DONGIA;
			}
			set
			{
				if ((this._DONGIA != value))
				{
					this.OnDONGIAChanging(value);
					this.SendPropertyChanging();
					this._DONGIA = value;
					this.SendPropertyChanged("DONGIA");
					this.OnDONGIAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HOADON_CT_HOADON", Storage="_HOADON", ThisKey="MA_HD", OtherKey="MA_HD", IsForeignKey=true)]
		public HOADON HOADON
		{
			get
			{
				return this._HOADON.Entity;
			}
			set
			{
				HOADON previousValue = this._HOADON.Entity;
				if (((previousValue != value) 
							|| (this._HOADON.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HOADON.Entity = null;
						previousValue.CT_HOADONs.Remove(this);
					}
					this._HOADON.Entity = value;
					if ((value != null))
					{
						value.CT_HOADONs.Add(this);
						this._MA_HD = value.MA_HD;
					}
					else
					{
						this._MA_HD = default(int);
					}
					this.SendPropertyChanged("HOADON");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SANPHAM_CT_HOADON", Storage="_SANPHAM", ThisKey="MA_SP", OtherKey="MA_SP", IsForeignKey=true)]
		public SANPHAM SANPHAM
		{
			get
			{
				return this._SANPHAM.Entity;
			}
			set
			{
				SANPHAM previousValue = this._SANPHAM.Entity;
				if (((previousValue != value) 
							|| (this._SANPHAM.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._SANPHAM.Entity = null;
						previousValue.CT_HOADONs.Remove(this);
					}
					this._SANPHAM.Entity = value;
					if ((value != null))
					{
						value.CT_HOADONs.Add(this);
						this._MA_SP = value.MA_SP;
					}
					else
					{
						this._MA_SP = default(int);
					}
					this.SendPropertyChanged("SANPHAM");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TINTUC")]
	public partial class TINTUC : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MA_TIN;
		
		private string _TIEUDE_TIN;
		
		private string _MOTA_TIN;
		
		private string _NOIDUNG_TIN;
		
		private System.Nullable<System.DateTime> _NGAYDANG_TIN;
		
		private System.Nullable<int> _MA_NV;
		
		private string _ANH_TIN;
		
		private System.Nullable<bool> _STATUS_TIN;
		
		private EntityRef<NHANVIEN> _NHANVIEN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMA_TINChanging(int value);
    partial void OnMA_TINChanged();
    partial void OnTIEUDE_TINChanging(string value);
    partial void OnTIEUDE_TINChanged();
    partial void OnMOTA_TINChanging(string value);
    partial void OnMOTA_TINChanged();
    partial void OnNOIDUNG_TINChanging(string value);
    partial void OnNOIDUNG_TINChanged();
    partial void OnNGAYDANG_TINChanging(System.Nullable<System.DateTime> value);
    partial void OnNGAYDANG_TINChanged();
    partial void OnMA_NVChanging(System.Nullable<int> value);
    partial void OnMA_NVChanged();
    partial void OnANH_TINChanging(string value);
    partial void OnANH_TINChanged();
    partial void OnSTATUS_TINChanging(System.Nullable<bool> value);
    partial void OnSTATUS_TINChanged();
    #endregion
		
		public TINTUC()
		{
			this._NHANVIEN = default(EntityRef<NHANVIEN>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MA_TIN", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MA_TIN
		{
			get
			{
				return this._MA_TIN;
			}
			set
			{
				if ((this._MA_TIN != value))
				{
					this.OnMA_TINChanging(value);
					this.SendPropertyChanging();
					this._MA_TIN = value;
					this.SendPropertyChanged("MA_TIN");
					this.OnMA_TINChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TIEUDE_TIN", DbType="NVarChar(100)")]
		public string TIEUDE_TIN
		{
			get
			{
				return this._TIEUDE_TIN;
			}
			set
			{
				if ((this._TIEUDE_TIN != value))
				{
					this.OnTIEUDE_TINChanging(value);
					this.SendPropertyChanging();
					this._TIEUDE_TIN = value;
					this.SendPropertyChanged("TIEUDE_TIN");
					this.OnTIEUDE_TINChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MOTA_TIN", DbType="NVarChar(200)")]
		public string MOTA_TIN
		{
			get
			{
				return this._MOTA_TIN;
			}
			set
			{
				if ((this._MOTA_TIN != value))
				{
					this.OnMOTA_TINChanging(value);
					this.SendPropertyChanging();
					this._MOTA_TIN = value;
					this.SendPropertyChanged("MOTA_TIN");
					this.OnMOTA_TINChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOIDUNG_TIN", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string NOIDUNG_TIN
		{
			get
			{
				return this._NOIDUNG_TIN;
			}
			set
			{
				if ((this._NOIDUNG_TIN != value))
				{
					this.OnNOIDUNG_TINChanging(value);
					this.SendPropertyChanging();
					this._NOIDUNG_TIN = value;
					this.SendPropertyChanged("NOIDUNG_TIN");
					this.OnNOIDUNG_TINChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYDANG_TIN", DbType="DateTime")]
		public System.Nullable<System.DateTime> NGAYDANG_TIN
		{
			get
			{
				return this._NGAYDANG_TIN;
			}
			set
			{
				if ((this._NGAYDANG_TIN != value))
				{
					this.OnNGAYDANG_TINChanging(value);
					this.SendPropertyChanging();
					this._NGAYDANG_TIN = value;
					this.SendPropertyChanged("NGAYDANG_TIN");
					this.OnNGAYDANG_TINChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MA_NV", DbType="Int")]
		public System.Nullable<int> MA_NV
		{
			get
			{
				return this._MA_NV;
			}
			set
			{
				if ((this._MA_NV != value))
				{
					if (this._NHANVIEN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMA_NVChanging(value);
					this.SendPropertyChanging();
					this._MA_NV = value;
					this.SendPropertyChanged("MA_NV");
					this.OnMA_NVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ANH_TIN", DbType="VarChar(100)")]
		public string ANH_TIN
		{
			get
			{
				return this._ANH_TIN;
			}
			set
			{
				if ((this._ANH_TIN != value))
				{
					this.OnANH_TINChanging(value);
					this.SendPropertyChanging();
					this._ANH_TIN = value;
					this.SendPropertyChanged("ANH_TIN");
					this.OnANH_TINChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATUS_TIN", DbType="Bit")]
		public System.Nullable<bool> STATUS_TIN
		{
			get
			{
				return this._STATUS_TIN;
			}
			set
			{
				if ((this._STATUS_TIN != value))
				{
					this.OnSTATUS_TINChanging(value);
					this.SendPropertyChanging();
					this._STATUS_TIN = value;
					this.SendPropertyChanged("STATUS_TIN");
					this.OnSTATUS_TINChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHANVIEN_TINTUC", Storage="_NHANVIEN", ThisKey="MA_NV", OtherKey="MA_NV", IsForeignKey=true)]
		public NHANVIEN NHANVIEN
		{
			get
			{
				return this._NHANVIEN.Entity;
			}
			set
			{
				NHANVIEN previousValue = this._NHANVIEN.Entity;
				if (((previousValue != value) 
							|| (this._NHANVIEN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NHANVIEN.Entity = null;
						previousValue.TINTUCs.Remove(this);
					}
					this._NHANVIEN.Entity = value;
					if ((value != null))
					{
						value.TINTUCs.Add(this);
						this._MA_NV = value.MA_NV;
					}
					else
					{
						this._MA_NV = default(Nullable<int>);
					}
					this.SendPropertyChanged("NHANVIEN");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CT_PHIEUNHAP")]
	public partial class CT_PHIEUNHAP : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MA_PN;
		
		private int _MA_SP;
		
		private System.Nullable<int> _SL_NHAP;
		
		private System.Nullable<double> _GIA_NHAP;
		
		private System.Nullable<double> _THANHTIEN;
		
		private EntityRef<PHIEUNHAP> _PHIEUNHAP;
		
		private EntityRef<SANPHAM> _SANPHAM;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMA_PNChanging(int value);
    partial void OnMA_PNChanged();
    partial void OnMA_SPChanging(int value);
    partial void OnMA_SPChanged();
    partial void OnSL_NHAPChanging(System.Nullable<int> value);
    partial void OnSL_NHAPChanged();
    partial void OnGIA_NHAPChanging(System.Nullable<double> value);
    partial void OnGIA_NHAPChanged();
    partial void OnTHANHTIENChanging(System.Nullable<double> value);
    partial void OnTHANHTIENChanged();
    #endregion
		
		public CT_PHIEUNHAP()
		{
			this._PHIEUNHAP = default(EntityRef<PHIEUNHAP>);
			this._SANPHAM = default(EntityRef<SANPHAM>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MA_PN", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MA_PN
		{
			get
			{
				return this._MA_PN;
			}
			set
			{
				if ((this._MA_PN != value))
				{
					if (this._PHIEUNHAP.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMA_PNChanging(value);
					this.SendPropertyChanging();
					this._MA_PN = value;
					this.SendPropertyChanged("MA_PN");
					this.OnMA_PNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MA_SP", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MA_SP
		{
			get
			{
				return this._MA_SP;
			}
			set
			{
				if ((this._MA_SP != value))
				{
					if (this._SANPHAM.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMA_SPChanging(value);
					this.SendPropertyChanging();
					this._MA_SP = value;
					this.SendPropertyChanged("MA_SP");
					this.OnMA_SPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SL_NHAP", DbType="Int")]
		public System.Nullable<int> SL_NHAP
		{
			get
			{
				return this._SL_NHAP;
			}
			set
			{
				if ((this._SL_NHAP != value))
				{
					this.OnSL_NHAPChanging(value);
					this.SendPropertyChanging();
					this._SL_NHAP = value;
					this.SendPropertyChanged("SL_NHAP");
					this.OnSL_NHAPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GIA_NHAP", DbType="Float")]
		public System.Nullable<double> GIA_NHAP
		{
			get
			{
				return this._GIA_NHAP;
			}
			set
			{
				if ((this._GIA_NHAP != value))
				{
					this.OnGIA_NHAPChanging(value);
					this.SendPropertyChanging();
					this._GIA_NHAP = value;
					this.SendPropertyChanged("GIA_NHAP");
					this.OnGIA_NHAPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_THANHTIEN", DbType="Float")]
		public System.Nullable<double> THANHTIEN
		{
			get
			{
				return this._THANHTIEN;
			}
			set
			{
				if ((this._THANHTIEN != value))
				{
					this.OnTHANHTIENChanging(value);
					this.SendPropertyChanging();
					this._THANHTIEN = value;
					this.SendPropertyChanged("THANHTIEN");
					this.OnTHANHTIENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PHIEUNHAP_CT_PHIEUNHAP", Storage="_PHIEUNHAP", ThisKey="MA_PN", OtherKey="MA_PN", IsForeignKey=true)]
		public PHIEUNHAP PHIEUNHAP
		{
			get
			{
				return this._PHIEUNHAP.Entity;
			}
			set
			{
				PHIEUNHAP previousValue = this._PHIEUNHAP.Entity;
				if (((previousValue != value) 
							|| (this._PHIEUNHAP.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PHIEUNHAP.Entity = null;
						previousValue.CT_PHIEUNHAPs.Remove(this);
					}
					this._PHIEUNHAP.Entity = value;
					if ((value != null))
					{
						value.CT_PHIEUNHAPs.Add(this);
						this._MA_PN = value.MA_PN;
					}
					else
					{
						this._MA_PN = default(int);
					}
					this.SendPropertyChanged("PHIEUNHAP");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SANPHAM_CT_PHIEUNHAP", Storage="_SANPHAM", ThisKey="MA_SP", OtherKey="MA_SP", IsForeignKey=true)]
		public SANPHAM SANPHAM
		{
			get
			{
				return this._SANPHAM.Entity;
			}
			set
			{
				SANPHAM previousValue = this._SANPHAM.Entity;
				if (((previousValue != value) 
							|| (this._SANPHAM.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._SANPHAM.Entity = null;
						previousValue.CT_PHIEUNHAPs.Remove(this);
					}
					this._SANPHAM.Entity = value;
					if ((value != null))
					{
						value.CT_PHIEUNHAPs.Add(this);
						this._MA_SP = value.MA_SP;
					}
					else
					{
						this._MA_SP = default(int);
					}
					this.SendPropertyChanged("SANPHAM");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DANHMUC")]
	public partial class DANHMUC : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MA_DM;
		
		private string _TEN_DM;
		
		private EntitySet<SANPHAM> _SANPHAMs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMA_DMChanging(int value);
    partial void OnMA_DMChanged();
    partial void OnTEN_DMChanging(string value);
    partial void OnTEN_DMChanged();
    #endregion
		
		public DANHMUC()
		{
			this._SANPHAMs = new EntitySet<SANPHAM>(new Action<SANPHAM>(this.attach_SANPHAMs), new Action<SANPHAM>(this.detach_SANPHAMs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MA_DM", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MA_DM
		{
			get
			{
				return this._MA_DM;
			}
			set
			{
				if ((this._MA_DM != value))
				{
					this.OnMA_DMChanging(value);
					this.SendPropertyChanging();
					this._MA_DM = value;
					this.SendPropertyChanged("MA_DM");
					this.OnMA_DMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TEN_DM", DbType="NVarChar(100)")]
		public string TEN_DM
		{
			get
			{
				return this._TEN_DM;
			}
			set
			{
				if ((this._TEN_DM != value))
				{
					this.OnTEN_DMChanging(value);
					this.SendPropertyChanging();
					this._TEN_DM = value;
					this.SendPropertyChanged("TEN_DM");
					this.OnTEN_DMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DANHMUC_SANPHAM", Storage="_SANPHAMs", ThisKey="MA_DM", OtherKey="MA_DM")]
		public EntitySet<SANPHAM> SANPHAMs
		{
			get
			{
				return this._SANPHAMs;
			}
			set
			{
				this._SANPHAMs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_SANPHAMs(SANPHAM entity)
		{
			this.SendPropertyChanging();
			entity.DANHMUC = this;
		}
		
		private void detach_SANPHAMs(SANPHAM entity)
		{
			this.SendPropertyChanging();
			entity.DANHMUC = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HINHANH_SP")]
	public partial class HINHANH_SP : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MA_SP;
		
		private string _ANH_SP;
		
		private System.Nullable<bool> _STT_HA;
		
		private EntityRef<SANPHAM> _SANPHAM;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMA_SPChanging(int value);
    partial void OnMA_SPChanged();
    partial void OnANH_SPChanging(string value);
    partial void OnANH_SPChanged();
    partial void OnSTT_HAChanging(System.Nullable<bool> value);
    partial void OnSTT_HAChanged();
    #endregion
		
		public HINHANH_SP()
		{
			this._SANPHAM = default(EntityRef<SANPHAM>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MA_SP", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MA_SP
		{
			get
			{
				return this._MA_SP;
			}
			set
			{
				if ((this._MA_SP != value))
				{
					if (this._SANPHAM.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMA_SPChanging(value);
					this.SendPropertyChanging();
					this._MA_SP = value;
					this.SendPropertyChanged("MA_SP");
					this.OnMA_SPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ANH_SP", DbType="VarChar(100) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ANH_SP
		{
			get
			{
				return this._ANH_SP;
			}
			set
			{
				if ((this._ANH_SP != value))
				{
					this.OnANH_SPChanging(value);
					this.SendPropertyChanging();
					this._ANH_SP = value;
					this.SendPropertyChanged("ANH_SP");
					this.OnANH_SPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STT_HA", DbType="Bit")]
		public System.Nullable<bool> STT_HA
		{
			get
			{
				return this._STT_HA;
			}
			set
			{
				if ((this._STT_HA != value))
				{
					this.OnSTT_HAChanging(value);
					this.SendPropertyChanging();
					this._STT_HA = value;
					this.SendPropertyChanged("STT_HA");
					this.OnSTT_HAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SANPHAM_HINHANH_SP", Storage="_SANPHAM", ThisKey="MA_SP", OtherKey="MA_SP", IsForeignKey=true)]
		public SANPHAM SANPHAM
		{
			get
			{
				return this._SANPHAM.Entity;
			}
			set
			{
				SANPHAM previousValue = this._SANPHAM.Entity;
				if (((previousValue != value) 
							|| (this._SANPHAM.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._SANPHAM.Entity = null;
						previousValue.HINHANH_SPs.Remove(this);
					}
					this._SANPHAM.Entity = value;
					if ((value != null))
					{
						value.HINHANH_SPs.Add(this);
						this._MA_SP = value.MA_SP;
					}
					else
					{
						this._MA_SP = default(int);
					}
					this.SendPropertyChanged("SANPHAM");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HOADON")]
	public partial class HOADON : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MA_HD;
		
		private System.Nullable<System.DateTime> _NGAYLAP_HD;
		
		private System.Nullable<double> _TONGTIEN_HD;
		
		private System.Nullable<int> _MA_KH;
		
		private System.Nullable<int> _MA_NV;
		
		private System.Nullable<bool> _STATUS_HD;
		
		private System.Nullable<bool> _STATUS_GH;
		
		private string _HOTEN_KN;
		
		private string _SDT_KN;
		
		private string _DIACHI_KN;
		
		private System.Nullable<System.DateTime> _NGAYGIAOHANG;
		
		private System.Nullable<bool> _STATUS_TT;
		
		private EntitySet<CT_HOADON> _CT_HOADONs;
		
		private EntityRef<KHACHHANG> _KHACHHANG;
		
		private EntityRef<NHANVIEN> _NHANVIEN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMA_HDChanging(int value);
    partial void OnMA_HDChanged();
    partial void OnNGAYLAP_HDChanging(System.Nullable<System.DateTime> value);
    partial void OnNGAYLAP_HDChanged();
    partial void OnTONGTIEN_HDChanging(System.Nullable<double> value);
    partial void OnTONGTIEN_HDChanged();
    partial void OnMA_KHChanging(System.Nullable<int> value);
    partial void OnMA_KHChanged();
    partial void OnMA_NVChanging(System.Nullable<int> value);
    partial void OnMA_NVChanged();
    partial void OnSTATUS_HDChanging(System.Nullable<bool> value);
    partial void OnSTATUS_HDChanged();
    partial void OnSTATUS_GHChanging(System.Nullable<bool> value);
    partial void OnSTATUS_GHChanged();
    partial void OnHOTEN_KNChanging(string value);
    partial void OnHOTEN_KNChanged();
    partial void OnSDT_KNChanging(string value);
    partial void OnSDT_KNChanged();
    partial void OnDIACHI_KNChanging(string value);
    partial void OnDIACHI_KNChanged();
    partial void OnNGAYGIAOHANGChanging(System.Nullable<System.DateTime> value);
    partial void OnNGAYGIAOHANGChanged();
    partial void OnSTATUS_TTChanging(System.Nullable<bool> value);
    partial void OnSTATUS_TTChanged();
    #endregion
		
		public HOADON()
		{
			this._CT_HOADONs = new EntitySet<CT_HOADON>(new Action<CT_HOADON>(this.attach_CT_HOADONs), new Action<CT_HOADON>(this.detach_CT_HOADONs));
			this._KHACHHANG = default(EntityRef<KHACHHANG>);
			this._NHANVIEN = default(EntityRef<NHANVIEN>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MA_HD", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MA_HD
		{
			get
			{
				return this._MA_HD;
			}
			set
			{
				if ((this._MA_HD != value))
				{
					this.OnMA_HDChanging(value);
					this.SendPropertyChanging();
					this._MA_HD = value;
					this.SendPropertyChanged("MA_HD");
					this.OnMA_HDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYLAP_HD", DbType="DateTime")]
		public System.Nullable<System.DateTime> NGAYLAP_HD
		{
			get
			{
				return this._NGAYLAP_HD;
			}
			set
			{
				if ((this._NGAYLAP_HD != value))
				{
					this.OnNGAYLAP_HDChanging(value);
					this.SendPropertyChanging();
					this._NGAYLAP_HD = value;
					this.SendPropertyChanged("NGAYLAP_HD");
					this.OnNGAYLAP_HDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TONGTIEN_HD", DbType="Float")]
		public System.Nullable<double> TONGTIEN_HD
		{
			get
			{
				return this._TONGTIEN_HD;
			}
			set
			{
				if ((this._TONGTIEN_HD != value))
				{
					this.OnTONGTIEN_HDChanging(value);
					this.SendPropertyChanging();
					this._TONGTIEN_HD = value;
					this.SendPropertyChanged("TONGTIEN_HD");
					this.OnTONGTIEN_HDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MA_KH", DbType="Int")]
		public System.Nullable<int> MA_KH
		{
			get
			{
				return this._MA_KH;
			}
			set
			{
				if ((this._MA_KH != value))
				{
					if (this._KHACHHANG.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMA_KHChanging(value);
					this.SendPropertyChanging();
					this._MA_KH = value;
					this.SendPropertyChanged("MA_KH");
					this.OnMA_KHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MA_NV", DbType="Int")]
		public System.Nullable<int> MA_NV
		{
			get
			{
				return this._MA_NV;
			}
			set
			{
				if ((this._MA_NV != value))
				{
					if (this._NHANVIEN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMA_NVChanging(value);
					this.SendPropertyChanging();
					this._MA_NV = value;
					this.SendPropertyChanged("MA_NV");
					this.OnMA_NVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATUS_HD", DbType="Bit")]
		public System.Nullable<bool> STATUS_HD
		{
			get
			{
				return this._STATUS_HD;
			}
			set
			{
				if ((this._STATUS_HD != value))
				{
					this.OnSTATUS_HDChanging(value);
					this.SendPropertyChanging();
					this._STATUS_HD = value;
					this.SendPropertyChanged("STATUS_HD");
					this.OnSTATUS_HDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATUS_GH", DbType="Bit")]
		public System.Nullable<bool> STATUS_GH
		{
			get
			{
				return this._STATUS_GH;
			}
			set
			{
				if ((this._STATUS_GH != value))
				{
					this.OnSTATUS_GHChanging(value);
					this.SendPropertyChanging();
					this._STATUS_GH = value;
					this.SendPropertyChanged("STATUS_GH");
					this.OnSTATUS_GHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HOTEN_KN", DbType="NVarChar(100)")]
		public string HOTEN_KN
		{
			get
			{
				return this._HOTEN_KN;
			}
			set
			{
				if ((this._HOTEN_KN != value))
				{
					this.OnHOTEN_KNChanging(value);
					this.SendPropertyChanging();
					this._HOTEN_KN = value;
					this.SendPropertyChanged("HOTEN_KN");
					this.OnHOTEN_KNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDT_KN", DbType="VarChar(15)")]
		public string SDT_KN
		{
			get
			{
				return this._SDT_KN;
			}
			set
			{
				if ((this._SDT_KN != value))
				{
					this.OnSDT_KNChanging(value);
					this.SendPropertyChanging();
					this._SDT_KN = value;
					this.SendPropertyChanged("SDT_KN");
					this.OnSDT_KNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIACHI_KN", DbType="NVarChar(100)")]
		public string DIACHI_KN
		{
			get
			{
				return this._DIACHI_KN;
			}
			set
			{
				if ((this._DIACHI_KN != value))
				{
					this.OnDIACHI_KNChanging(value);
					this.SendPropertyChanging();
					this._DIACHI_KN = value;
					this.SendPropertyChanged("DIACHI_KN");
					this.OnDIACHI_KNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYGIAOHANG", DbType="DateTime")]
		public System.Nullable<System.DateTime> NGAYGIAOHANG
		{
			get
			{
				return this._NGAYGIAOHANG;
			}
			set
			{
				if ((this._NGAYGIAOHANG != value))
				{
					this.OnNGAYGIAOHANGChanging(value);
					this.SendPropertyChanging();
					this._NGAYGIAOHANG = value;
					this.SendPropertyChanged("NGAYGIAOHANG");
					this.OnNGAYGIAOHANGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATUS_TT", DbType="Bit")]
		public System.Nullable<bool> STATUS_TT
		{
			get
			{
				return this._STATUS_TT;
			}
			set
			{
				if ((this._STATUS_TT != value))
				{
					this.OnSTATUS_TTChanging(value);
					this.SendPropertyChanging();
					this._STATUS_TT = value;
					this.SendPropertyChanged("STATUS_TT");
					this.OnSTATUS_TTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HOADON_CT_HOADON", Storage="_CT_HOADONs", ThisKey="MA_HD", OtherKey="MA_HD")]
		public EntitySet<CT_HOADON> CT_HOADONs
		{
			get
			{
				return this._CT_HOADONs;
			}
			set
			{
				this._CT_HOADONs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KHACHHANG_HOADON", Storage="_KHACHHANG", ThisKey="MA_KH", OtherKey="MA_KH", IsForeignKey=true)]
		public KHACHHANG KHACHHANG
		{
			get
			{
				return this._KHACHHANG.Entity;
			}
			set
			{
				KHACHHANG previousValue = this._KHACHHANG.Entity;
				if (((previousValue != value) 
							|| (this._KHACHHANG.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KHACHHANG.Entity = null;
						previousValue.HOADONs.Remove(this);
					}
					this._KHACHHANG.Entity = value;
					if ((value != null))
					{
						value.HOADONs.Add(this);
						this._MA_KH = value.MA_KH;
					}
					else
					{
						this._MA_KH = default(Nullable<int>);
					}
					this.SendPropertyChanged("KHACHHANG");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHANVIEN_HOADON", Storage="_NHANVIEN", ThisKey="MA_NV", OtherKey="MA_NV", IsForeignKey=true)]
		public NHANVIEN NHANVIEN
		{
			get
			{
				return this._NHANVIEN.Entity;
			}
			set
			{
				NHANVIEN previousValue = this._NHANVIEN.Entity;
				if (((previousValue != value) 
							|| (this._NHANVIEN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NHANVIEN.Entity = null;
						previousValue.HOADONs.Remove(this);
					}
					this._NHANVIEN.Entity = value;
					if ((value != null))
					{
						value.HOADONs.Add(this);
						this._MA_NV = value.MA_NV;
					}
					else
					{
						this._MA_NV = default(Nullable<int>);
					}
					this.SendPropertyChanged("NHANVIEN");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CT_HOADONs(CT_HOADON entity)
		{
			this.SendPropertyChanging();
			entity.HOADON = this;
		}
		
		private void detach_CT_HOADONs(CT_HOADON entity)
		{
			this.SendPropertyChanging();
			entity.HOADON = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KHACHHANG")]
	public partial class KHACHHANG : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MA_KH;
		
		private string _HOTEN_KH;
		
		private string _USERNAME_KH;
		
		private System.Nullable<byte> _CAPDO_KH;
		
		private System.Nullable<int> _TICHDIEM_KH;
		
		private string _SDT_KH;
		
		private string _PASSWORD_KH;
		
		private EntitySet<HOADON> _HOADONs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMA_KHChanging(int value);
    partial void OnMA_KHChanged();
    partial void OnHOTEN_KHChanging(string value);
    partial void OnHOTEN_KHChanged();
    partial void OnUSERNAME_KHChanging(string value);
    partial void OnUSERNAME_KHChanged();
    partial void OnCAPDO_KHChanging(System.Nullable<byte> value);
    partial void OnCAPDO_KHChanged();
    partial void OnTICHDIEM_KHChanging(System.Nullable<int> value);
    partial void OnTICHDIEM_KHChanged();
    partial void OnSDT_KHChanging(string value);
    partial void OnSDT_KHChanged();
    partial void OnPASSWORD_KHChanging(string value);
    partial void OnPASSWORD_KHChanged();
    #endregion
		
		public KHACHHANG()
		{
			this._HOADONs = new EntitySet<HOADON>(new Action<HOADON>(this.attach_HOADONs), new Action<HOADON>(this.detach_HOADONs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MA_KH", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MA_KH
		{
			get
			{
				return this._MA_KH;
			}
			set
			{
				if ((this._MA_KH != value))
				{
					this.OnMA_KHChanging(value);
					this.SendPropertyChanging();
					this._MA_KH = value;
					this.SendPropertyChanged("MA_KH");
					this.OnMA_KHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HOTEN_KH", DbType="NVarChar(100)")]
		public string HOTEN_KH
		{
			get
			{
				return this._HOTEN_KH;
			}
			set
			{
				if ((this._HOTEN_KH != value))
				{
					this.OnHOTEN_KHChanging(value);
					this.SendPropertyChanging();
					this._HOTEN_KH = value;
					this.SendPropertyChanged("HOTEN_KH");
					this.OnHOTEN_KHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USERNAME_KH", DbType="VarChar(100)")]
		public string USERNAME_KH
		{
			get
			{
				return this._USERNAME_KH;
			}
			set
			{
				if ((this._USERNAME_KH != value))
				{
					this.OnUSERNAME_KHChanging(value);
					this.SendPropertyChanging();
					this._USERNAME_KH = value;
					this.SendPropertyChanged("USERNAME_KH");
					this.OnUSERNAME_KHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CAPDO_KH", DbType="TinyInt")]
		public System.Nullable<byte> CAPDO_KH
		{
			get
			{
				return this._CAPDO_KH;
			}
			set
			{
				if ((this._CAPDO_KH != value))
				{
					this.OnCAPDO_KHChanging(value);
					this.SendPropertyChanging();
					this._CAPDO_KH = value;
					this.SendPropertyChanged("CAPDO_KH");
					this.OnCAPDO_KHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TICHDIEM_KH", DbType="Int")]
		public System.Nullable<int> TICHDIEM_KH
		{
			get
			{
				return this._TICHDIEM_KH;
			}
			set
			{
				if ((this._TICHDIEM_KH != value))
				{
					this.OnTICHDIEM_KHChanging(value);
					this.SendPropertyChanging();
					this._TICHDIEM_KH = value;
					this.SendPropertyChanged("TICHDIEM_KH");
					this.OnTICHDIEM_KHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDT_KH", DbType="VarChar(15)")]
		public string SDT_KH
		{
			get
			{
				return this._SDT_KH;
			}
			set
			{
				if ((this._SDT_KH != value))
				{
					this.OnSDT_KHChanging(value);
					this.SendPropertyChanging();
					this._SDT_KH = value;
					this.SendPropertyChanged("SDT_KH");
					this.OnSDT_KHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PASSWORD_KH", DbType="VarChar(40)")]
		public string PASSWORD_KH
		{
			get
			{
				return this._PASSWORD_KH;
			}
			set
			{
				if ((this._PASSWORD_KH != value))
				{
					this.OnPASSWORD_KHChanging(value);
					this.SendPropertyChanging();
					this._PASSWORD_KH = value;
					this.SendPropertyChanged("PASSWORD_KH");
					this.OnPASSWORD_KHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KHACHHANG_HOADON", Storage="_HOADONs", ThisKey="MA_KH", OtherKey="MA_KH")]
		public EntitySet<HOADON> HOADONs
		{
			get
			{
				return this._HOADONs;
			}
			set
			{
				this._HOADONs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_HOADONs(HOADON entity)
		{
			this.SendPropertyChanging();
			entity.KHACHHANG = this;
		}
		
		private void detach_HOADONs(HOADON entity)
		{
			this.SendPropertyChanging();
			entity.KHACHHANG = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NHACUNGCAP")]
	public partial class NHACUNGCAP : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MA_NCC;
		
		private string _TEN_NCC;
		
		private string _DIACHI_NCC;
		
		private string _DT_NCC;
		
		private EntitySet<PHIEUNHAP> _PHIEUNHAPs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMA_NCCChanging(int value);
    partial void OnMA_NCCChanged();
    partial void OnTEN_NCCChanging(string value);
    partial void OnTEN_NCCChanged();
    partial void OnDIACHI_NCCChanging(string value);
    partial void OnDIACHI_NCCChanged();
    partial void OnDT_NCCChanging(string value);
    partial void OnDT_NCCChanged();
    #endregion
		
		public NHACUNGCAP()
		{
			this._PHIEUNHAPs = new EntitySet<PHIEUNHAP>(new Action<PHIEUNHAP>(this.attach_PHIEUNHAPs), new Action<PHIEUNHAP>(this.detach_PHIEUNHAPs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MA_NCC", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MA_NCC
		{
			get
			{
				return this._MA_NCC;
			}
			set
			{
				if ((this._MA_NCC != value))
				{
					this.OnMA_NCCChanging(value);
					this.SendPropertyChanging();
					this._MA_NCC = value;
					this.SendPropertyChanged("MA_NCC");
					this.OnMA_NCCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TEN_NCC", DbType="NVarChar(100)")]
		public string TEN_NCC
		{
			get
			{
				return this._TEN_NCC;
			}
			set
			{
				if ((this._TEN_NCC != value))
				{
					this.OnTEN_NCCChanging(value);
					this.SendPropertyChanging();
					this._TEN_NCC = value;
					this.SendPropertyChanged("TEN_NCC");
					this.OnTEN_NCCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIACHI_NCC", DbType="NVarChar(100)")]
		public string DIACHI_NCC
		{
			get
			{
				return this._DIACHI_NCC;
			}
			set
			{
				if ((this._DIACHI_NCC != value))
				{
					this.OnDIACHI_NCCChanging(value);
					this.SendPropertyChanging();
					this._DIACHI_NCC = value;
					this.SendPropertyChanged("DIACHI_NCC");
					this.OnDIACHI_NCCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DT_NCC", DbType="VarChar(15)")]
		public string DT_NCC
		{
			get
			{
				return this._DT_NCC;
			}
			set
			{
				if ((this._DT_NCC != value))
				{
					this.OnDT_NCCChanging(value);
					this.SendPropertyChanging();
					this._DT_NCC = value;
					this.SendPropertyChanged("DT_NCC");
					this.OnDT_NCCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHACUNGCAP_PHIEUNHAP", Storage="_PHIEUNHAPs", ThisKey="MA_NCC", OtherKey="MA_NCC")]
		public EntitySet<PHIEUNHAP> PHIEUNHAPs
		{
			get
			{
				return this._PHIEUNHAPs;
			}
			set
			{
				this._PHIEUNHAPs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_PHIEUNHAPs(PHIEUNHAP entity)
		{
			this.SendPropertyChanging();
			entity.NHACUNGCAP = this;
		}
		
		private void detach_PHIEUNHAPs(PHIEUNHAP entity)
		{
			this.SendPropertyChanging();
			entity.NHACUNGCAP = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NHANVIEN")]
	public partial class NHANVIEN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MA_NV;
		
		private string _HOTEN_NV;
		
		private string _CMMD_NV;
		
		private string _USERNAME_NV;
		
		private string _PASSWORD_NV;
		
		private System.Nullable<bool> _STT_NV;
		
		private EntitySet<TINTUC> _TINTUCs;
		
		private EntitySet<HOADON> _HOADONs;
		
		private EntitySet<PHIEUNHAP> _PHIEUNHAPs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMA_NVChanging(int value);
    partial void OnMA_NVChanged();
    partial void OnHOTEN_NVChanging(string value);
    partial void OnHOTEN_NVChanged();
    partial void OnCMMD_NVChanging(string value);
    partial void OnCMMD_NVChanged();
    partial void OnUSERNAME_NVChanging(string value);
    partial void OnUSERNAME_NVChanged();
    partial void OnPASSWORD_NVChanging(string value);
    partial void OnPASSWORD_NVChanged();
    partial void OnSTT_NVChanging(System.Nullable<bool> value);
    partial void OnSTT_NVChanged();
    #endregion
		
		public NHANVIEN()
		{
			this._TINTUCs = new EntitySet<TINTUC>(new Action<TINTUC>(this.attach_TINTUCs), new Action<TINTUC>(this.detach_TINTUCs));
			this._HOADONs = new EntitySet<HOADON>(new Action<HOADON>(this.attach_HOADONs), new Action<HOADON>(this.detach_HOADONs));
			this._PHIEUNHAPs = new EntitySet<PHIEUNHAP>(new Action<PHIEUNHAP>(this.attach_PHIEUNHAPs), new Action<PHIEUNHAP>(this.detach_PHIEUNHAPs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MA_NV", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MA_NV
		{
			get
			{
				return this._MA_NV;
			}
			set
			{
				if ((this._MA_NV != value))
				{
					this.OnMA_NVChanging(value);
					this.SendPropertyChanging();
					this._MA_NV = value;
					this.SendPropertyChanged("MA_NV");
					this.OnMA_NVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HOTEN_NV", DbType="NVarChar(50)")]
		public string HOTEN_NV
		{
			get
			{
				return this._HOTEN_NV;
			}
			set
			{
				if ((this._HOTEN_NV != value))
				{
					this.OnHOTEN_NVChanging(value);
					this.SendPropertyChanging();
					this._HOTEN_NV = value;
					this.SendPropertyChanged("HOTEN_NV");
					this.OnHOTEN_NVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CMMD_NV", DbType="VarChar(12)")]
		public string CMMD_NV
		{
			get
			{
				return this._CMMD_NV;
			}
			set
			{
				if ((this._CMMD_NV != value))
				{
					this.OnCMMD_NVChanging(value);
					this.SendPropertyChanging();
					this._CMMD_NV = value;
					this.SendPropertyChanged("CMMD_NV");
					this.OnCMMD_NVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USERNAME_NV", DbType="VarChar(40)")]
		public string USERNAME_NV
		{
			get
			{
				return this._USERNAME_NV;
			}
			set
			{
				if ((this._USERNAME_NV != value))
				{
					this.OnUSERNAME_NVChanging(value);
					this.SendPropertyChanging();
					this._USERNAME_NV = value;
					this.SendPropertyChanged("USERNAME_NV");
					this.OnUSERNAME_NVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PASSWORD_NV", DbType="VarChar(40)")]
		public string PASSWORD_NV
		{
			get
			{
				return this._PASSWORD_NV;
			}
			set
			{
				if ((this._PASSWORD_NV != value))
				{
					this.OnPASSWORD_NVChanging(value);
					this.SendPropertyChanging();
					this._PASSWORD_NV = value;
					this.SendPropertyChanged("PASSWORD_NV");
					this.OnPASSWORD_NVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STT_NV", DbType="Bit")]
		public System.Nullable<bool> STT_NV
		{
			get
			{
				return this._STT_NV;
			}
			set
			{
				if ((this._STT_NV != value))
				{
					this.OnSTT_NVChanging(value);
					this.SendPropertyChanging();
					this._STT_NV = value;
					this.SendPropertyChanged("STT_NV");
					this.OnSTT_NVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHANVIEN_TINTUC", Storage="_TINTUCs", ThisKey="MA_NV", OtherKey="MA_NV")]
		public EntitySet<TINTUC> TINTUCs
		{
			get
			{
				return this._TINTUCs;
			}
			set
			{
				this._TINTUCs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHANVIEN_HOADON", Storage="_HOADONs", ThisKey="MA_NV", OtherKey="MA_NV")]
		public EntitySet<HOADON> HOADONs
		{
			get
			{
				return this._HOADONs;
			}
			set
			{
				this._HOADONs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHANVIEN_PHIEUNHAP", Storage="_PHIEUNHAPs", ThisKey="MA_NV", OtherKey="MA_NV")]
		public EntitySet<PHIEUNHAP> PHIEUNHAPs
		{
			get
			{
				return this._PHIEUNHAPs;
			}
			set
			{
				this._PHIEUNHAPs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TINTUCs(TINTUC entity)
		{
			this.SendPropertyChanging();
			entity.NHANVIEN = this;
		}
		
		private void detach_TINTUCs(TINTUC entity)
		{
			this.SendPropertyChanging();
			entity.NHANVIEN = null;
		}
		
		private void attach_HOADONs(HOADON entity)
		{
			this.SendPropertyChanging();
			entity.NHANVIEN = this;
		}
		
		private void detach_HOADONs(HOADON entity)
		{
			this.SendPropertyChanging();
			entity.NHANVIEN = null;
		}
		
		private void attach_PHIEUNHAPs(PHIEUNHAP entity)
		{
			this.SendPropertyChanging();
			entity.NHANVIEN = this;
		}
		
		private void detach_PHIEUNHAPs(PHIEUNHAP entity)
		{
			this.SendPropertyChanging();
			entity.NHANVIEN = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PHIEUNHAP")]
	public partial class PHIEUNHAP : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MA_PN;
		
		private System.Nullable<int> _MA_NCC;
		
		private System.Nullable<double> _TONGTIEN_PH;
		
		private System.Nullable<System.DateTime> _NGAY_NHAP;
		
		private System.Nullable<int> _MA_NV;
		
		private EntitySet<CT_PHIEUNHAP> _CT_PHIEUNHAPs;
		
		private EntityRef<NHACUNGCAP> _NHACUNGCAP;
		
		private EntityRef<NHANVIEN> _NHANVIEN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMA_PNChanging(int value);
    partial void OnMA_PNChanged();
    partial void OnMA_NCCChanging(System.Nullable<int> value);
    partial void OnMA_NCCChanged();
    partial void OnTONGTIEN_PHChanging(System.Nullable<double> value);
    partial void OnTONGTIEN_PHChanged();
    partial void OnNGAY_NHAPChanging(System.Nullable<System.DateTime> value);
    partial void OnNGAY_NHAPChanged();
    partial void OnMA_NVChanging(System.Nullable<int> value);
    partial void OnMA_NVChanged();
    #endregion
		
		public PHIEUNHAP()
		{
			this._CT_PHIEUNHAPs = new EntitySet<CT_PHIEUNHAP>(new Action<CT_PHIEUNHAP>(this.attach_CT_PHIEUNHAPs), new Action<CT_PHIEUNHAP>(this.detach_CT_PHIEUNHAPs));
			this._NHACUNGCAP = default(EntityRef<NHACUNGCAP>);
			this._NHANVIEN = default(EntityRef<NHANVIEN>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MA_PN", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MA_PN
		{
			get
			{
				return this._MA_PN;
			}
			set
			{
				if ((this._MA_PN != value))
				{
					this.OnMA_PNChanging(value);
					this.SendPropertyChanging();
					this._MA_PN = value;
					this.SendPropertyChanged("MA_PN");
					this.OnMA_PNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MA_NCC", DbType="Int")]
		public System.Nullable<int> MA_NCC
		{
			get
			{
				return this._MA_NCC;
			}
			set
			{
				if ((this._MA_NCC != value))
				{
					if (this._NHACUNGCAP.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMA_NCCChanging(value);
					this.SendPropertyChanging();
					this._MA_NCC = value;
					this.SendPropertyChanged("MA_NCC");
					this.OnMA_NCCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TONGTIEN_PH", DbType="Float")]
		public System.Nullable<double> TONGTIEN_PH
		{
			get
			{
				return this._TONGTIEN_PH;
			}
			set
			{
				if ((this._TONGTIEN_PH != value))
				{
					this.OnTONGTIEN_PHChanging(value);
					this.SendPropertyChanging();
					this._TONGTIEN_PH = value;
					this.SendPropertyChanged("TONGTIEN_PH");
					this.OnTONGTIEN_PHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAY_NHAP", DbType="DateTime")]
		public System.Nullable<System.DateTime> NGAY_NHAP
		{
			get
			{
				return this._NGAY_NHAP;
			}
			set
			{
				if ((this._NGAY_NHAP != value))
				{
					this.OnNGAY_NHAPChanging(value);
					this.SendPropertyChanging();
					this._NGAY_NHAP = value;
					this.SendPropertyChanged("NGAY_NHAP");
					this.OnNGAY_NHAPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MA_NV", DbType="Int")]
		public System.Nullable<int> MA_NV
		{
			get
			{
				return this._MA_NV;
			}
			set
			{
				if ((this._MA_NV != value))
				{
					if (this._NHANVIEN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMA_NVChanging(value);
					this.SendPropertyChanging();
					this._MA_NV = value;
					this.SendPropertyChanged("MA_NV");
					this.OnMA_NVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PHIEUNHAP_CT_PHIEUNHAP", Storage="_CT_PHIEUNHAPs", ThisKey="MA_PN", OtherKey="MA_PN")]
		public EntitySet<CT_PHIEUNHAP> CT_PHIEUNHAPs
		{
			get
			{
				return this._CT_PHIEUNHAPs;
			}
			set
			{
				this._CT_PHIEUNHAPs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHACUNGCAP_PHIEUNHAP", Storage="_NHACUNGCAP", ThisKey="MA_NCC", OtherKey="MA_NCC", IsForeignKey=true)]
		public NHACUNGCAP NHACUNGCAP
		{
			get
			{
				return this._NHACUNGCAP.Entity;
			}
			set
			{
				NHACUNGCAP previousValue = this._NHACUNGCAP.Entity;
				if (((previousValue != value) 
							|| (this._NHACUNGCAP.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NHACUNGCAP.Entity = null;
						previousValue.PHIEUNHAPs.Remove(this);
					}
					this._NHACUNGCAP.Entity = value;
					if ((value != null))
					{
						value.PHIEUNHAPs.Add(this);
						this._MA_NCC = value.MA_NCC;
					}
					else
					{
						this._MA_NCC = default(Nullable<int>);
					}
					this.SendPropertyChanged("NHACUNGCAP");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHANVIEN_PHIEUNHAP", Storage="_NHANVIEN", ThisKey="MA_NV", OtherKey="MA_NV", IsForeignKey=true)]
		public NHANVIEN NHANVIEN
		{
			get
			{
				return this._NHANVIEN.Entity;
			}
			set
			{
				NHANVIEN previousValue = this._NHANVIEN.Entity;
				if (((previousValue != value) 
							|| (this._NHANVIEN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NHANVIEN.Entity = null;
						previousValue.PHIEUNHAPs.Remove(this);
					}
					this._NHANVIEN.Entity = value;
					if ((value != null))
					{
						value.PHIEUNHAPs.Add(this);
						this._MA_NV = value.MA_NV;
					}
					else
					{
						this._MA_NV = default(Nullable<int>);
					}
					this.SendPropertyChanged("NHANVIEN");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CT_PHIEUNHAPs(CT_PHIEUNHAP entity)
		{
			this.SendPropertyChanging();
			entity.PHIEUNHAP = this;
		}
		
		private void detach_CT_PHIEUNHAPs(CT_PHIEUNHAP entity)
		{
			this.SendPropertyChanging();
			entity.PHIEUNHAP = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SANPHAM")]
	public partial class SANPHAM : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MA_SP;
		
		private string _TEN_SP;
		
		private System.Nullable<double> _GIA_SP;
		
		private System.Nullable<int> _MA_DM;
		
		private string _CT_SP;
		
		private string _AVA_SP;
		
		private System.Nullable<System.DateTime> _NGAYCAPNHAT_SP;
		
		private System.Nullable<int> _SL_TON;
		
		private System.Nullable<bool> _STATUS_SP;
		
		private EntitySet<CT_HOADON> _CT_HOADONs;
		
		private EntitySet<CT_PHIEUNHAP> _CT_PHIEUNHAPs;
		
		private EntitySet<HINHANH_SP> _HINHANH_SPs;
		
		private EntityRef<DANHMUC> _DANHMUC;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMA_SPChanging(int value);
    partial void OnMA_SPChanged();
    partial void OnTEN_SPChanging(string value);
    partial void OnTEN_SPChanged();
    partial void OnGIA_SPChanging(System.Nullable<double> value);
    partial void OnGIA_SPChanged();
    partial void OnMA_DMChanging(System.Nullable<int> value);
    partial void OnMA_DMChanged();
    partial void OnCT_SPChanging(string value);
    partial void OnCT_SPChanged();
    partial void OnAVA_SPChanging(string value);
    partial void OnAVA_SPChanged();
    partial void OnNGAYCAPNHAT_SPChanging(System.Nullable<System.DateTime> value);
    partial void OnNGAYCAPNHAT_SPChanged();
    partial void OnSL_TONChanging(System.Nullable<int> value);
    partial void OnSL_TONChanged();
    partial void OnSTATUS_SPChanging(System.Nullable<bool> value);
    partial void OnSTATUS_SPChanged();
    #endregion
		
		public SANPHAM()
		{
			this._CT_HOADONs = new EntitySet<CT_HOADON>(new Action<CT_HOADON>(this.attach_CT_HOADONs), new Action<CT_HOADON>(this.detach_CT_HOADONs));
			this._CT_PHIEUNHAPs = new EntitySet<CT_PHIEUNHAP>(new Action<CT_PHIEUNHAP>(this.attach_CT_PHIEUNHAPs), new Action<CT_PHIEUNHAP>(this.detach_CT_PHIEUNHAPs));
			this._HINHANH_SPs = new EntitySet<HINHANH_SP>(new Action<HINHANH_SP>(this.attach_HINHANH_SPs), new Action<HINHANH_SP>(this.detach_HINHANH_SPs));
			this._DANHMUC = default(EntityRef<DANHMUC>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MA_SP", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MA_SP
		{
			get
			{
				return this._MA_SP;
			}
			set
			{
				if ((this._MA_SP != value))
				{
					this.OnMA_SPChanging(value);
					this.SendPropertyChanging();
					this._MA_SP = value;
					this.SendPropertyChanged("MA_SP");
					this.OnMA_SPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TEN_SP", DbType="NVarChar(100)")]
		public string TEN_SP
		{
			get
			{
				return this._TEN_SP;
			}
			set
			{
				if ((this._TEN_SP != value))
				{
					this.OnTEN_SPChanging(value);
					this.SendPropertyChanging();
					this._TEN_SP = value;
					this.SendPropertyChanged("TEN_SP");
					this.OnTEN_SPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GIA_SP", DbType="Float")]
		public System.Nullable<double> GIA_SP
		{
			get
			{
				return this._GIA_SP;
			}
			set
			{
				if ((this._GIA_SP != value))
				{
					this.OnGIA_SPChanging(value);
					this.SendPropertyChanging();
					this._GIA_SP = value;
					this.SendPropertyChanged("GIA_SP");
					this.OnGIA_SPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MA_DM", DbType="Int")]
		public System.Nullable<int> MA_DM
		{
			get
			{
				return this._MA_DM;
			}
			set
			{
				if ((this._MA_DM != value))
				{
					if (this._DANHMUC.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMA_DMChanging(value);
					this.SendPropertyChanging();
					this._MA_DM = value;
					this.SendPropertyChanged("MA_DM");
					this.OnMA_DMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CT_SP", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string CT_SP
		{
			get
			{
				return this._CT_SP;
			}
			set
			{
				if ((this._CT_SP != value))
				{
					this.OnCT_SPChanging(value);
					this.SendPropertyChanging();
					this._CT_SP = value;
					this.SendPropertyChanged("CT_SP");
					this.OnCT_SPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AVA_SP", DbType="VarChar(100)")]
		public string AVA_SP
		{
			get
			{
				return this._AVA_SP;
			}
			set
			{
				if ((this._AVA_SP != value))
				{
					this.OnAVA_SPChanging(value);
					this.SendPropertyChanging();
					this._AVA_SP = value;
					this.SendPropertyChanged("AVA_SP");
					this.OnAVA_SPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYCAPNHAT_SP", DbType="DateTime")]
		public System.Nullable<System.DateTime> NGAYCAPNHAT_SP
		{
			get
			{
				return this._NGAYCAPNHAT_SP;
			}
			set
			{
				if ((this._NGAYCAPNHAT_SP != value))
				{
					this.OnNGAYCAPNHAT_SPChanging(value);
					this.SendPropertyChanging();
					this._NGAYCAPNHAT_SP = value;
					this.SendPropertyChanged("NGAYCAPNHAT_SP");
					this.OnNGAYCAPNHAT_SPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SL_TON", DbType="Int")]
		public System.Nullable<int> SL_TON
		{
			get
			{
				return this._SL_TON;
			}
			set
			{
				if ((this._SL_TON != value))
				{
					this.OnSL_TONChanging(value);
					this.SendPropertyChanging();
					this._SL_TON = value;
					this.SendPropertyChanged("SL_TON");
					this.OnSL_TONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATUS_SP", DbType="Bit")]
		public System.Nullable<bool> STATUS_SP
		{
			get
			{
				return this._STATUS_SP;
			}
			set
			{
				if ((this._STATUS_SP != value))
				{
					this.OnSTATUS_SPChanging(value);
					this.SendPropertyChanging();
					this._STATUS_SP = value;
					this.SendPropertyChanged("STATUS_SP");
					this.OnSTATUS_SPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SANPHAM_CT_HOADON", Storage="_CT_HOADONs", ThisKey="MA_SP", OtherKey="MA_SP")]
		public EntitySet<CT_HOADON> CT_HOADONs
		{
			get
			{
				return this._CT_HOADONs;
			}
			set
			{
				this._CT_HOADONs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SANPHAM_CT_PHIEUNHAP", Storage="_CT_PHIEUNHAPs", ThisKey="MA_SP", OtherKey="MA_SP")]
		public EntitySet<CT_PHIEUNHAP> CT_PHIEUNHAPs
		{
			get
			{
				return this._CT_PHIEUNHAPs;
			}
			set
			{
				this._CT_PHIEUNHAPs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SANPHAM_HINHANH_SP", Storage="_HINHANH_SPs", ThisKey="MA_SP", OtherKey="MA_SP")]
		public EntitySet<HINHANH_SP> HINHANH_SPs
		{
			get
			{
				return this._HINHANH_SPs;
			}
			set
			{
				this._HINHANH_SPs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DANHMUC_SANPHAM", Storage="_DANHMUC", ThisKey="MA_DM", OtherKey="MA_DM", IsForeignKey=true)]
		public DANHMUC DANHMUC
		{
			get
			{
				return this._DANHMUC.Entity;
			}
			set
			{
				DANHMUC previousValue = this._DANHMUC.Entity;
				if (((previousValue != value) 
							|| (this._DANHMUC.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DANHMUC.Entity = null;
						previousValue.SANPHAMs.Remove(this);
					}
					this._DANHMUC.Entity = value;
					if ((value != null))
					{
						value.SANPHAMs.Add(this);
						this._MA_DM = value.MA_DM;
					}
					else
					{
						this._MA_DM = default(Nullable<int>);
					}
					this.SendPropertyChanged("DANHMUC");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CT_HOADONs(CT_HOADON entity)
		{
			this.SendPropertyChanging();
			entity.SANPHAM = this;
		}
		
		private void detach_CT_HOADONs(CT_HOADON entity)
		{
			this.SendPropertyChanging();
			entity.SANPHAM = null;
		}
		
		private void attach_CT_PHIEUNHAPs(CT_PHIEUNHAP entity)
		{
			this.SendPropertyChanging();
			entity.SANPHAM = this;
		}
		
		private void detach_CT_PHIEUNHAPs(CT_PHIEUNHAP entity)
		{
			this.SendPropertyChanging();
			entity.SANPHAM = null;
		}
		
		private void attach_HINHANH_SPs(HINHANH_SP entity)
		{
			this.SendPropertyChanging();
			entity.SANPHAM = this;
		}
		
		private void detach_HINHANH_SPs(HINHANH_SP entity)
		{
			this.SendPropertyChanging();
			entity.SANPHAM = null;
		}
	}
}
#pragma warning restore 1591
